FROM php:5.6-apache

ARG user_id
ARG group_id
ARG typo3_version

MAINTAINER Mario Seidel

#install general utils
RUN apt-get update -qq && \
    apt-get install -qqy vim \
    && rm -rf /var/lib/apt/lists/*

#install requirements for typo3
RUN apt-get update -qq && \
    apt-get install -qqy git \
        libxml2-dev libfreetype6-dev \
        graphicsmagick \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        zlib1g-dev \
        locales \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8

ENV LANG de_DE.utf8

RUN a2enmod rewrite

#enable PHP Extensions
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-install -j$(nproc) mysqli soap gd zip mbstring

#set TYPO3 php configuration
RUN echo 'always_populate_raw_post_data = -1\nmax_execution_time = 240\nmax_input_vars = 1500\nupload_max_filesize = 32M\npost_max_size = 32M' > /usr/local/etc/php/conf.d/typo3.ini

#install composer
RUN cd /usr/local/bin/ && \
        php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php && \
#        php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === 'fd26ce67e3b237fffd5e5544b45b0d92c41a4afe3e3f778e942e43ce6be197b9cdc7c251dcde6e2a52297ea269370680') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); }" && \
        php composer-setup.php && \
        php -r "unlink('composer-setup.php');" && \
        chmod +x /usr/local/bin/composer.phar

CMD ["composer.phar", "diagnose"]
